TASK: ssl
TRAIN:
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  MIXED_PRECISION: True
MODEL:
  NUM_CLASSES: 128
  MODEL_NAME: ContrastiveModel
  ARCH: slow_c2d
  ARCH: slow
  LOSS_FUNC: contrastive_loss
  DROPOUT_RATE: 0.0
  HEAD_ACT: none
CONTRASTIVE:
  T: 0.1
  NUM_MLP_LAYERS: 3 # default 1
  SEQUENTIAL: True  # def fault
  MOCO_MULTI_VIEW_QUEUE: True # default: False
  MOMENTUM: 0.994 # default 0.5 ours: 0.999
  MOMENTUM_ANNEALING: True # default false
  TYPE: moco # default mem
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_CROP_NUM_TEMPORAL: 4  # default 1
  TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  TRAIN_JITTER_SCALES_RELATIVE: [0.2, 0.766]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  SSL_MOCOV2_AUG: True
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_JITTER: True # default false
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_LABEL_SEPARATOR: " "
DATA_LOADER:
  NUM_WORKERS: 8
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.05
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 200
  WARMUP_EPOCHS: 35.0
  MOMENTUM: 0.9
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
NUM_GPUS: 8
RNG_SEED: 0
OUTPUT_DIR: .
